spring:
  datasource:
    hikari:
      # rewriteBatchedStatements=true: mysql에서 bulk-insert를 사용하기 위한 옵션
      jdbc-url: jdbc:mysql://127.0.0.1:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update  # 테이블이 없을 시 생성, 엔티티가 변경되었을 시 스키마 변경
    show-sql: true
  batch:
    initialize-schema: never  # always, embedded(기본값, 내장DB일 때만 실행), never(메타 테이블이 자동으로 생성되지 않게 함)
